/**
 * Phase 1 — governance program unit tests.
 *
 * Coverage map (subtask numbers from spec/phases/phase-01-governance-program.md §4):
 *   4.1  initialize: owner + defaults + route_count
 *   4.2  set_defaults: owner-only
 *   4.3  whitelist_route: owner ✓, active admin ✓, non-admin ✗
 *   4.4  whitelist_route + get_route_terms: defaults when no overrides
 *   4.5  whitelist_route + get_route_terms: overrides when fully specified
 *   4.6  whitelist_route + get_route_terms: partial overrides resolve correctly
 *   4.7  whitelist_route: length-cap reverts
 *   4.8  disable_route: flips approved; is_route_whitelisted → false
 *   4.9  is_route_whitelisted: missing PDA → false (no revert)
 *   4.10 update_route_terms: tri-state Keep / Set / RevertToDefault
 *   4.11 add_admin: owner ✓; non-owner ✗
 *   4.12 remove_admin: flips is_active; previously-active admin loses authority
 *   4.13 add_admin re-activation: removed admin can be re-added (idempotent)
 *   4.14 whitelist_route re-activation: disabled route can be re-enabled
 *
 * All tests use Codama-generated typed Kit instruction builders from
 * `tests/clients/governance/` (regenerated by `pnpm gen-clients`). No
 * hand-rolled instruction discriminators.
 */

import { beforeEach, describe, expect, it } from 'vitest';
import {
  generateKeyPairSigner,
  getBooleanDecoder,
  lamports,
  type Address,
  type KeyPairSigner,
} from '@solana/kit';

import {
  bootstrapGovernance,
  makeClient,
  sendAndDecodeReturnData,
  type GovernanceBootstrap,
} from './setup.ts';

import {
  GOVERNANCE_PROGRAM_ADDRESS,
  // PDA helpers
  findAdminRecordPda,
  findRoutePda,
  // Instruction builders
  getAddAdminInstructionAsync,
  getDisableRouteInstructionAsync,
  getGetRouteTermsInstructionAsync,
  getIsRouteWhitelistedInstruction,
  getRemoveAdminInstructionAsync,
  getSetDefaultsInstructionAsync,
  getUpdateRouteTermsInstructionAsync,
  getWhitelistRouteInstructionAsync,
  // Account decoders
  getGovernanceConfigDecoder,
  getRouteAccountDecoder,
  // Type codecs
  getResolvedTermsDecoder,
  u32Update,
  u64Update,
} from './clients/governance/src/generated/index.ts';

// ─── Constants used across tests ─────────────────────────────────────────
const FLIGHT = { flightId: 'AA100', origin: 'JFK', destination: 'SFO' } as const;
const DEFAULT_PREMIUM = 1_000_000n; // 1 USDC
const DEFAULT_PAYOFF = 10_000_000n; // 10 USDC
const DEFAULT_DELAY = 2;

// ─── Per-test fixture builder ────────────────────────────────────────────
type Client = Awaited<ReturnType<typeof makeClient>>;

interface Fixture {
  client: Client;
  bootstrap: GovernanceBootstrap;
}

async function freshFixture(): Promise<Fixture> {
  const client = await makeClient();
  const bootstrap = await bootstrapGovernance(client, {
    premium: DEFAULT_PREMIUM,
    payoff: DEFAULT_PAYOFF,
    delayHours: DEFAULT_DELAY,
  });
  return { client, bootstrap };
}

async function fundedSigner(client: Client): Promise<KeyPairSigner> {
  const signer = await generateKeyPairSigner();
  await client.airdrop(signer.address, lamports(2_000_000_000n)); // 2 SOL
  return signer;
}

function readAccount(client: Client, addr: Address): Uint8Array {
  const acc = client.svm.getAccount(addr);
  if (!acc.exists) throw new Error(`account ${addr} missing`);
  return acc.data;
}

// ─── 4.1 initialize ───────────────────────────────────────────────────────

describe('Phase 1 — governance: initialize', () => {
  it('4.1 sets owner, defaults, and route_count = 0', async () => {
    const { client, bootstrap } = await freshFixture();
    const data = readAccount(client, bootstrap.configPda);
    const decoded = getGovernanceConfigDecoder().decode(data);

    expect(decoded.owner).toBe(client.payer.address);
    expect(decoded.defaultPremium).toBe(DEFAULT_PREMIUM);
    expect(decoded.defaultPayoff).toBe(DEFAULT_PAYOFF);
    expect(decoded.defaultDelayHours).toBe(DEFAULT_DELAY);
    expect(decoded.routeCount).toBe(0);
  });
});

// ─── 4.2 set_defaults ────────────────────────────────────────────────────

describe('Phase 1 — governance: set_defaults', () => {
  let f: Fixture;
  beforeEach(async () => { f = await freshFixture(); });

  it('owner can set new defaults', async () => {
    const ix = await getSetDefaultsInstructionAsync({
      owner: f.client.payer,
      premium: 500_000n,
      payoff: 5_000_000n,
      delayHours: 4,
    });
    await f.client.sendTransaction([ix]);
    const decoded = getGovernanceConfigDecoder().decode(readAccount(f.client, f.bootstrap.configPda));
    expect(decoded.defaultPremium).toBe(500_000n);
    expect(decoded.defaultPayoff).toBe(5_000_000n);
    expect(decoded.defaultDelayHours).toBe(4);
  });

  it('4.2 non-owner reverts', async () => {
    const stranger = await fundedSigner(f.client);
    const ix = await getSetDefaultsInstructionAsync({
      owner: stranger,
      premium: 1n,
      payoff: 1n,
      delayHours: 1,
    });
    await expect(f.client.sendTransaction([ix])).rejects.toThrow();
  });
});

// ─── 4.3 / 4.7 whitelist_route — auth and length caps ───────────────────

describe('Phase 1 — governance: whitelist_route auth + length caps', () => {
  let f: Fixture;
  beforeEach(async () => { f = await freshFixture(); });

  /**
   * Build a `whitelist_route` ix. The optional `adminRecord` account in
   * Anchor's `Option<Account<...>>` pattern is treated as None when the
   * passed address equals the program ID (sentinel). When `caller` is the
   * owner, we want None — Codama would otherwise auto-derive a PDA from
   * `caller`, and Anchor would fail to load that non-existent account
   * with `AccountNotInitialized`.
   */
  async function whitelistAs(caller: KeyPairSigner, callerIsOwner: boolean) {
    return getWhitelistRouteInstructionAsync({
      caller,
      adminRecord: callerIsOwner ? GOVERNANCE_PROGRAM_ADDRESS : undefined,
      flightId: FLIGHT.flightId,
      origin: FLIGHT.origin,
      destination: FLIGHT.destination,
      premium: null,
      payoff: null,
      delayHours: null,
    });
  }

  it('4.3a owner succeeds; route_count increments', async () => {
    const ix = await whitelistAs(f.client.payer, true);
    await f.client.sendTransaction([ix]);
    const decoded = getGovernanceConfigDecoder().decode(readAccount(f.client, f.bootstrap.configPda));
    expect(decoded.routeCount).toBe(1);
  });

  it('4.3b active admin succeeds', async () => {
    const admin = await fundedSigner(f.client);
    const addIx = await getAddAdminInstructionAsync({
      owner: f.client.payer,
      admin: admin.address,
    });
    await f.client.sendTransaction([addIx]);

    const wIx = await whitelistAs(admin, false);
    await f.client.sendTransaction([wIx]);
    const decoded = getGovernanceConfigDecoder().decode(readAccount(f.client, f.bootstrap.configPda));
    expect(decoded.routeCount).toBe(1);
  });

  it('4.3c non-admin random caller reverts', async () => {
    const stranger = await fundedSigner(f.client);
    const ix = await whitelistAs(stranger, false);
    await expect(f.client.sendTransaction([ix])).rejects.toThrow();
  });

  it('4.7 length caps revert with RouteFieldTooLong', async () => {
    const longFlight = 'X'.repeat(20); // > MAX_FLIGHT_ID_LEN (16)
    const ix = await getWhitelistRouteInstructionAsync({
      caller: f.client.payer,
      adminRecord: GOVERNANCE_PROGRAM_ADDRESS,
      flightId: longFlight,
      origin: FLIGHT.origin,
      destination: FLIGHT.destination,
      premium: null, payoff: null, delayHours: null,
    });
    await expect(f.client.sendTransaction([ix])).rejects.toThrow();
  });
});

// ─── 4.4 / 4.5 / 4.6 get_route_terms resolution ──────────────────────────

describe('Phase 1 — governance: get_route_terms resolution', () => {
  async function buildAndRead(
    overrides: { premium?: bigint | null; payoff?: bigint | null; delayHours?: number | null } = {},
  ) {
    const f = await freshFixture();
    const wIx = await getWhitelistRouteInstructionAsync({
      caller: f.client.payer,
      adminRecord: GOVERNANCE_PROGRAM_ADDRESS, // owner caller → no admin record
      flightId: FLIGHT.flightId,
      origin: FLIGHT.origin,
      destination: FLIGHT.destination,
      premium: overrides.premium === undefined ? null : overrides.premium,
      payoff: overrides.payoff === undefined ? null : overrides.payoff,
      delayHours: overrides.delayHours === undefined ? null : overrides.delayHours,
    });
    await f.client.sendTransaction([wIx]);

    const rIx = await getGetRouteTermsInstructionAsync({
      flightId: FLIGHT.flightId,
      origin: FLIGHT.origin,
      destination: FLIGHT.destination,
    });
    return sendAndDecodeReturnData(
      f.client,
      rIx,
      getResolvedTermsDecoder(),
      GOVERNANCE_PROGRAM_ADDRESS,
    );
  }

  it('4.4 no overrides → returns defaults', async () => {
    const r = await buildAndRead({});
    expect(r.premium).toBe(DEFAULT_PREMIUM);
    expect(r.payoff).toBe(DEFAULT_PAYOFF);
    expect(r.delayHours).toBe(DEFAULT_DELAY);
  });

  it('4.5 full overrides → returns overrides', async () => {
    const r = await buildAndRead({ premium: 7n, payoff: 70n, delayHours: 7 });
    expect(r.premium).toBe(7n);
    expect(r.payoff).toBe(70n);
    expect(r.delayHours).toBe(7);
  });

  it('4.6 partial overrides → resolved correctly', async () => {
    // Only premium overridden; payoff and delay_hours fall back to defaults.
    const r = await buildAndRead({ premium: 999n });
    expect(r.premium).toBe(999n);
    expect(r.payoff).toBe(DEFAULT_PAYOFF);
    expect(r.delayHours).toBe(DEFAULT_DELAY);
  });
});

// ─── 4.8 / 4.9 disable_route + is_route_whitelisted ─────────────────────

describe('Phase 1 — governance: disable_route + is_route_whitelisted', () => {
  let f: Fixture;
  beforeEach(async () => { f = await freshFixture(); });

  async function whitelist() {
    const ix = await getWhitelistRouteInstructionAsync({
      caller: f.client.payer,
      adminRecord: GOVERNANCE_PROGRAM_ADDRESS,
      flightId: FLIGHT.flightId,
      origin: FLIGHT.origin,
      destination: FLIGHT.destination,
      premium: null, payoff: null, delayHours: null,
    });
    await f.client.sendTransaction([ix]);
  }

  async function readApproved(): Promise<boolean> {
    const [routePda] = await findRoutePda({
      flightId: FLIGHT.flightId,
      origin: FLIGHT.origin,
      destination: FLIGHT.destination,
    });
    const ix = getIsRouteWhitelistedInstruction({
      route: routePda,
      flightId: FLIGHT.flightId,
      origin: FLIGHT.origin,
      destination: FLIGHT.destination,
    });
    return sendAndDecodeReturnData(
      f.client,
      ix,
      getBooleanDecoder(),
      GOVERNANCE_PROGRAM_ADDRESS,
    );
  }

  it('4.8 disable_route flips approved → is_route_whitelisted returns false', async () => {
    await whitelist();
    expect(await readApproved()).toBe(true);

    const dIx = await getDisableRouteInstructionAsync({
      caller: f.client.payer,
      adminRecord: GOVERNANCE_PROGRAM_ADDRESS,
      flightId: FLIGHT.flightId,
      origin: FLIGHT.origin,
      destination: FLIGHT.destination,
    });
    await f.client.sendTransaction([dIx]);

    expect(await readApproved()).toBe(false);
  });

  it('4.9 missing route PDA → is_route_whitelisted returns false (no revert)', async () => {
    // No whitelist call — the route PDA does not exist.
    expect(await readApproved()).toBe(false);
  });
});

// ─── 4.10 update_route_terms tri-state ──────────────────────────────────

describe('Phase 1 — governance: update_route_terms', () => {
  it('4.10 Set / Keep / RevertToDefault each behave correctly', async () => {
    const f = await freshFixture();

    // Initial: full overrides {premium=7, payoff=70, delay=7}
    const wIx = await getWhitelistRouteInstructionAsync({
      caller: f.client.payer,
      adminRecord: GOVERNANCE_PROGRAM_ADDRESS,
      flightId: FLIGHT.flightId,
      origin: FLIGHT.origin,
      destination: FLIGHT.destination,
      premium: 7n, payoff: 70n, delayHours: 7,
    });
    await f.client.sendTransaction([wIx]);

    // Update: premium → Set(8), payoff → Keep, delayHours → RevertToDefault
    const uIx = await getUpdateRouteTermsInstructionAsync({
      caller: f.client.payer,
      adminRecord: GOVERNANCE_PROGRAM_ADDRESS,
      flightId: FLIGHT.flightId,
      origin: FLIGHT.origin,
      destination: FLIGHT.destination,
      premium: u64Update('Set', [8n]),
      payoff: u64Update('Keep'),
      delayHours: u32Update('RevertToDefault'),
    });
    await f.client.sendTransaction([uIx]);

    const rIx = await getGetRouteTermsInstructionAsync({
      flightId: FLIGHT.flightId,
      origin: FLIGHT.origin,
      destination: FLIGHT.destination,
    });
    const r = await sendAndDecodeReturnData(
      f.client,
      rIx,
      getResolvedTermsDecoder(),
      GOVERNANCE_PROGRAM_ADDRESS,
    );
    expect(r.premium).toBe(8n); // Set
    expect(r.payoff).toBe(70n); // Keep — preserves the override
    expect(r.delayHours).toBe(DEFAULT_DELAY); // RevertToDefault
  });
});

// ─── 4.11 / 4.12 / 4.13 add_admin / remove_admin ─────────────────────────

describe('Phase 1 — governance: admin lifecycle', () => {
  it('4.11 owner adds admin; AdminRecord active; non-owner add reverts', async () => {
    const f = await freshFixture();
    const admin = await fundedSigner(f.client);

    const ix = await getAddAdminInstructionAsync({
      owner: f.client.payer,
      admin: admin.address,
    });
    await f.client.sendTransaction([ix]);

    const [adminPda] = await findAdminRecordPda({ admin: admin.address });
    const data = readAccount(f.client, adminPda);
    // AdminRecord layout: 8-byte discriminator | admin: Pubkey | is_active: bool | bump: u8
    // is_active sits at offset 8 + 32 = 40
    expect(data[40]).toBe(1);

    // Non-owner attempting add_admin reverts.
    const stranger = await fundedSigner(f.client);
    const candidate = await generateKeyPairSigner();
    const badIx = await getAddAdminInstructionAsync({
      owner: stranger,
      admin: candidate.address,
    });
    await expect(f.client.sendTransaction([badIx])).rejects.toThrow();
  });

  it('4.12 remove_admin flips is_active; deactivated admin cannot whitelist', async () => {
    const f = await freshFixture();
    const admin = await fundedSigner(f.client);

    await f.client.sendTransaction([
      await getAddAdminInstructionAsync({ owner: f.client.payer, admin: admin.address }),
    ]);
    await f.client.sendTransaction([
      await getRemoveAdminInstructionAsync({ owner: f.client.payer, admin: admin.address }),
    ]);

    const [adminPda] = await findAdminRecordPda({ admin: admin.address });
    expect(readAccount(f.client, adminPda)[40]).toBe(0);

    // Now-inactive admin attempts whitelist_route — must revert.
    // Codama auto-derives the admin_record PDA from the caller; the
    // existing-but-inactive AdminRecord deserializes successfully and the
    // program checks `is_active`, hitting `UnauthorizedAdmin`.
    const wIx = await getWhitelistRouteInstructionAsync({
      caller: admin,
      flightId: FLIGHT.flightId,
      origin: FLIGHT.origin,
      destination: FLIGHT.destination,
      premium: null, payoff: null, delayHours: null,
    });
    await expect(f.client.sendTransaction([wIx])).rejects.toThrow();
  });

  it('4.13 add_admin re-activates a previously-removed admin', async () => {
    const f = await freshFixture();
    const admin = await fundedSigner(f.client);

    await f.client.sendTransaction([
      await getAddAdminInstructionAsync({ owner: f.client.payer, admin: admin.address }),
    ]);
    await f.client.sendTransaction([
      await getRemoveAdminInstructionAsync({ owner: f.client.payer, admin: admin.address }),
    ]);
    // The third tx is byte-identical to the first (same payer, args, blockhash),
    // which would yield a duplicate signature and "transaction already processed".
    // Rotate the recent blockhash so the message — and signature — differ.
    f.client.svm.expireBlockhash();
    await f.client.sendTransaction([
      await getAddAdminInstructionAsync({ owner: f.client.payer, admin: admin.address }),
    ]);

    const [adminPda] = await findAdminRecordPda({ admin: admin.address });
    expect(readAccount(f.client, adminPda)[40]).toBe(1); // re-activated
  });
});

// ─── 4.14 whitelist_route re-activation ─────────────────────────────────

describe('Phase 1 — governance: route re-activation', () => {
  it('4.14 disable then whitelist_route again with new overrides re-activates the route', async () => {
    const f = await freshFixture();

    // First whitelist with overrides A.
    await f.client.sendTransaction([
      await getWhitelistRouteInstructionAsync({
        caller: f.client.payer,
        adminRecord: GOVERNANCE_PROGRAM_ADDRESS,
        flightId: FLIGHT.flightId,
        origin: FLIGHT.origin,
        destination: FLIGHT.destination,
        premium: 11n, payoff: 110n, delayHours: 1,
      }),
    ]);

    // Disable.
    await f.client.sendTransaction([
      await getDisableRouteInstructionAsync({
        caller: f.client.payer,
        adminRecord: GOVERNANCE_PROGRAM_ADDRESS,
        flightId: FLIGHT.flightId,
        origin: FLIGHT.origin,
        destination: FLIGHT.destination,
      }),
    ]);

    // Re-whitelist with overrides B (different values, exercising overwrite).
    await f.client.sendTransaction([
      await getWhitelistRouteInstructionAsync({
        caller: f.client.payer,
        adminRecord: GOVERNANCE_PROGRAM_ADDRESS,
        flightId: FLIGHT.flightId,
        origin: FLIGHT.origin,
        destination: FLIGHT.destination,
        premium: 22n, payoff: 220n, delayHours: 5,
      }),
    ]);

    const [routePda] = await findRoutePda({
      flightId: FLIGHT.flightId,
      origin: FLIGHT.origin,
      destination: FLIGHT.destination,
    });
    const route = getRouteAccountDecoder().decode(readAccount(f.client, routePda));
    expect(route.approved).toBe(true);
    // Compare option values via __option marker that Kit emits.
    expect(route.premium).toEqual({ __option: 'Some', value: 22n });
    expect(route.payoff).toEqual({ __option: 'Some', value: 220n });
    expect(route.delayHours).toEqual({ __option: 'Some', value: 5 });

    // route_count must NOT have been incremented again (idempotent re-whitelist).
    const cfg = getGovernanceConfigDecoder().decode(readAccount(f.client, f.bootstrap.configPda));
    expect(cfg.routeCount).toBe(1);
  });
});
