[toolchain]
anchor_version = "1.0.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
controller = "G4v4i3LoLX7v3cEb3cehNGWMHbvHArRyPSEiZmg5VSot"
flight_pool = "GW1yq7rswXBect6yR1RWtU7Q7AmY5wWMnq58a1JGcwVq"
governance = "6d6QXsZRQ1fXp8wEXFTm4uXAbLWarPKX6XJLcNUY8rcT"
oracle_aggregator = "EmTfS5EjPRABDuDrM5AW5TWi73eCCJnejpLAcwaxMCr6"
vault = "3yzuTtfGYUBsdhXf4QGeq9MUGj5RDNLj3hFPtsWGkj8p"

[programs.localnet]
controller = "G4v4i3LoLX7v3cEb3cehNGWMHbvHArRyPSEiZmg5VSot"
flight_pool = "GW1yq7rswXBect6yR1RWtU7Q7AmY5wWMnq58a1JGcwVq"
governance = "6d6QXsZRQ1fXp8wEXFTm4uXAbLWarPKX6XJLcNUY8rcT"
oracle_aggregator = "EmTfS5EjPRABDuDrM5AW5TWi73eCCJnejpLAcwaxMCr6"
vault = "3yzuTtfGYUBsdhXf4QGeq9MUGj5RDNLj3hFPtsWGkj8p"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm --filter @sentinel/contracts test"

[hooks]

[surfpool]
startup_wait = 5000
shutdown_wait = 2000
rpc_port = 8899
host = "127.0.0.1"
log_level = "info"
block_production_mode = "clock"
